[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "GsX4b44N2vkDjnZPLucGV7ou5qxADN2N6BZ7zU8vnJ1X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"

[toolchain]
anchor_version = "0.29.0"